const userData = [
  {
    firstName: "John Doe",
    type: "Traiteur",
    email: "johndoe@mail.com",
    phone: "123-456-7890",
    address: "261 Erdman Ford",
    city: "East Daphne",
    state: "Kentucky",
  },
  {
    firstName: "Jane Doe",
    type: "Fleuriste",
    email: "janedoe@mail.com",
    phone: "123-456-7890",
    address: "769 Dominic Grove",
    city: "Columbus",
    state: "Ohio",
  },
  {
    firstName: "Joe Doe",
    type: "Jeux bois",
    email: "joedoe@mail.com",
    phone: "123-456-7890",
    address: "566 Brakus Inlet",
    city: "South Linda",
    state: "West Virginia",
  },
  {
    firstName: "Kevin Vandy",
    type: "DJ",
    email: "kevinvandy@mail.com",
    phone: "123-456-7890",
    address: "722 Emie Stream",
    city: "Lincoln",
    state: "Nebraska",
  },
  {
    firstName: "Joshua Rolluffs",
    type: "Photographe",
    email: "joshuarolluffs@mail.com",
    phone: "123-456-7890",
    address: "32188 Larkin Turnpike",
    city: "Charleston",
    state: "South Carolina",
  },
  {
    firstName: "Joe Doe",
    type: "Jeux bois",
    email: "joedoe@mail.com",
    phone: "123-456-7890",
    address: "566 Brakus Inlet",
    city: "South Linda",
    state: "West Virginia",
  },
  {
    firstName: "Kevin Vandy",
    type: "DJ",
    email: "kevinvandy@mail.com",
    phone: "123-456-7890",
    address: "722 Emie Stream",
    city: "Lincoln",
    state: "Nebraska",
  },
];

export default userData;
